winget install -e --id Google.Chrome
winget install -e --id Discord.Discord
winget install -e --id Mojang.MinecraftLauncher
winget install -e --id Git.Git
winget install -e --id Microsoft.PowerToys
winget install -e --id Microsoft.VisualStudioCode
winget install -e --id Microsoft.VisualStudio.2022.Community.Preview
winget install -e --id RARLab.WinRAR
winget install -e --id Spotify.Spotify
winget install -e --id xanderfrangos.twinkletray
winget install -e --id OpenJS.NodeJS.LTS
winget install -e --id Microsoft.WindowsTerminal
winget install -e --id Microsoft.WindowsSubsystemForLinux
winget install -e --id Canonical.Ubuntu.2204
winget install -e --id Oracle.MySQL
winget install Wintoys -s msstore
winget install -e --id voidtools.Everything
winget install -e --id Notion.Notion
winget install -e --id NotionRepackaged.NotionEnhanced
